version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_website
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
