version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_website
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq_service
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped

  hostapd:
    build:
      context: .
      dockerfile: ../hostapd/Dockerfile
    container_name: hostapd_service
    volumes:
      - ./config/hostapd.conf:/etc/hostapd/hostapd.conf
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped
    devices:
      - "/dev/net/tun:/dev/net/tun"
