version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_website
    volumes:
      - ./website:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: unless-stopped

  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: Dockerfile
    container_name: dnsmasq_service
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped

  hostapd:
    build:
      context: ./hostapd
      dockerfile: Dockerfile
    container_name: hostapd_service
    volumes:
      - ./config/hostapd.conf:/etc/hostapd/hostapd.conf
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped
    devices:
      - "/dev/net/tun:/dev/net/tun"
